inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/**/*'
    - 'config/**/*.yml'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

# Turn on Rails cops
Rails:
  Enabled: true

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# --- Layout ---

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceInsideBrackets:
  Exclude:
    - 'config/environments/production.rb' # that's how Rails generates it

# --- Metrics ---

Metrics/AbcSize:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # 2 methods but they seem readable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # a method that is simply a case statement

# because this isn't 1994
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/services/preserved_object_handler.rb' # 2 lines 121
    - 'spec/services/preserved_object_handler_spec.rb' # 3 lines are longer

Metrics/MethodLength:
  Max: 25

# --- Naming ---

Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'

# --- Performance ---

# --- Rails ---

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb' # that's how Rails generates it

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # we're using touch on purpose

# --- RSpec ---

RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/load_fixtures_helper.rb' # being careful to avoid state leakage

RSpec/ExampleLength:
  Max: 50

RSpec/MultipleExpectations:
  Max: 5

# we like 'expect(x).to receive' better than 'have_received'
RSpec/MessageSpies:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
    - 'spec/lib/audit/moab_to_catalog_spec.rb'
    - 'spec/services/preserved_object_handler_spec.rb'

# --- Style ---

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb' # that's how rspec-rails generates it

Style/BracesAroundHashParameters:
  Exclude:
    - app/services/preserved_object_handler.rb # code is clearer with the braces

Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb' # that's how Rails generates it
    - 'app/helpers/application_helper.rb' # that's how Rails generates it
    - 'app/models/application_record.rb' # that's how Rails generates it
    - 'config/application.rb' # that's how Rails generates it

Style/FormatString:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # using interpolated strings

Style/FormatStringToken:
  EnforcedStyle: template # using interpolated strings in PreservedObjectHandler

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/spring.rb' # that's how Rails generates it

# because ' vs " isn't a big deal for readability or maintainability or execution time
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'Rakefile' # because [:spec, :rubocop ] isn't a big deal
