inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/**/*'
    - 'config/**/*.yml'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

# Turn on Rails cops
Rails:
  Enabled: true

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'


Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false


Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# because this isn't 1994
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20


Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/preserved_object.rb' # because we're using touch on purpose


RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/models/preserved_object_spec.rb' # after(:all) is fine here

RSpec/ExampleLength:
  Max: 50

RSpec/MessageSpies:
  Exclude:
    - 'spec/models/preserved_object_spec.rb' # have_received is a pain here

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/controllers/moab_storage_controller_spec.rb'
    - 'spec/models/preserved_object_spec.rb'

RSpec/NestedGroups:
  Max: 4

RSpec/NamedSubject:
  Enabled: false


Style/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'Rakefile' # because [:spec, :rubocop ] isn't a big deal
