inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/**/*'
    - 'config/**/*.yml'
    - 'config/environments/*.rb'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

# Turn on Rails cops
Rails:
  Enabled: true

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# --- Layout ---

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceInsideBrackets:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # line 126 is clearer with the spaces

# --- Lint ---
Lint/HandleExceptions:
  Exclude:
    - 'spec/lib/audit/moab_to_catalog_spec.rb' # So method does not stop executing and can test the correct case

Lint/RescueWithoutErrorClass:
  Exclude:
    - 'spec/lib/audit/moab_to_catalog_spec.rb' # So method does not stop executing and can test the correct case


# --- Metrics ---

Metrics/AbcSize:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # methods still readable; shameless green
    - 'lib/audit/moab_to_catalog.rb' # .xxx_for_all_storage_roots is decidedly readable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/services/preserved_object_handler.rb' # check_existence shameless green

Metrics/BlockNesting:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # check_existence shameless green

Metrics/ClassLength:
  Exclude:
    - 'app/services/preserved_object_handler.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # update_online_version (shameless green)
    - 'app/services/preserved_object_handler_results.rb' # logger_severity_level is simply a case statement

# because this isn't 1994
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/services/preserved_object_handler.rb' # line 269 is 121
    - 'app/services/preserved_object_handler_results.rb' # line 35 is 121
    - 'spec/lib/audit/moab_to_catalog_spec.rb' # 1 line 126
    - 'spec/services/preserved_object_handler_confirm_version_spec.rb'
    - 'spec/services/preserved_object_handler_create_spec.rb'
    - 'spec/services/preserved_object_handler_update_version_spec.rb'
    - 'spec/services/shared_examples_preserved_object_handler.rb'
    - 'spec/models/status_spec.rb' # Line length of 132 for better readability
    - 'spec/services/preserved_object_handler_check_exist_spec.rb' # 17 lines, but who's counting, officer?

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'app/services/preserved_object_handler.rb' # check_existence shameless green

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # update_online_version shameless green

# --- Naming ---

Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'

# --- Performance ---

# --- Rails ---

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/audit/moab_to_catalog.rb' # yes, we want to use puts statements

Rails/SkipsModelValidations:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # we're using touch on purpose

# --- RSpec ---

RSpec/BeforeAfterAll:
  Exclude:
    # we use after(:all) specifically to prevent state leakage
    - 'spec/load_fixtures_helper.rb'
    - 'spec/models/preservation_policy_spec.rb'

RSpec/ExampleLength:
  Max: 25

RSpec/InstanceVariable:
  Exclude:
    - 'spec/services/preserved_object_handler_update_version_spec.rb' # we can't use let instead of @

# we like 'expect(x).to receive' better than 'have_received'
RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
    - 'spec/lib/audit/moab_to_catalog_spec.rb'
    - 'spec/services/preserved_object_handler_confirm_version_spec.rb'
    - 'spec/services/preserved_object_handler_create_spec.rb'
    - 'spec/services/preserved_object_handler_update_version_spec.rb'
    - 'spec/services/preserved_object_handler_check_exist_spec.rb'

# --- Style ---

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb' # that's how rspec-rails generates it

Style/BlockDelimiters:
  Exclude:
    - 'spec/*/*' # rspec expect statements look ugly with do-end instead of {}

Style/BracesAroundHashParameters:
  Exclude:
    - app/services/preserved_object_handler.rb # code is clearer with the braces

Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb' # that's how Rails generates it
    - 'app/helpers/application_helper.rb' # that's how Rails generates it
    - 'app/models/application_record.rb' # that's how Rails generates it
    - 'config/application.rb' # that's how Rails generates it

Style/FormatStringToken:
  EnforcedStyle: template # using interpolated strings in PreservedObjectHandlerResults

Style/GuardClause:
  Exclude:
    - app/services/preserved_object_handler.rb # update_status method easy to read as is

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/spring.rb' # that's how Rails generates it

# because ' vs " isn't a big deal for readability or maintainability or execution time
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'Rakefile' # because [:spec, :rubocop] isn't a big deal
