inherit_from: .rubocop_todo.yml

# Turn on RSpec cops
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - 'Gemfile.lock'
    - '**/*.md'
    - 'bin/**/*'
    - 'config/**/*.yml'
    - 'config/environments/*.rb'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

# Turn on Rails cops
Rails:
  Enabled: true

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

# --- Layout ---

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceInsideBrackets:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # line 126 is clearer with the spaces

# --- Lint ---
Lint/HandleExceptions:
  Exclude:
    - 'spec/lib/audit/moab_to_catalog_spec.rb' # So method does not stop executing and can test the correct case

Lint/RescueWithoutErrorClass:
  Exclude:
    - 'spec/lib/audit/moab_to_catalog_spec.rb' # So method does not stop executing and can test the correct case


# --- Metrics ---

Metrics/AbcSize:
  Exclude:
    - 'app/services/checksum_validator.rb' # methods still readable; shameless green
    - 'app/services/preserved_object_handler.rb' # methods still readable; shameless green
    - 'app/services/audit_results.rb' # method still readable
    - 'lib/audit/catalog_to_moab.rb' # .check_version_all_dirs is decidedly readable
    - 'lib/audit/checksum.rb' # .validate_disk_all_dirs is decidedly readable
    - 'lib/audit/moab_to_catalog.rb' # .xxx_for_all_storage_roots is decidedly readable

Metrics/BlockLength:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # check_existence shameless green
    - 'spec/**/*'

Metrics/BlockNesting:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # check_existence shameless green

Metrics/ClassLength:
  Exclude:
    - 'app/services/checksum_validator.rb'
    - 'app/services/preserved_object_handler.rb'
    - 'app/services/audit_results.rb'
    - 'lib/audit/catalog_to_moab.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # update_online_version (shameless green)
    - 'app/services/audit_results.rb' # logger_severity_level is simply a case statement
    - 'lib/audit/catalog_to_moab.rb' # check_catalog_version (shameless green)

# because this isn't 1994
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'Rakefile' # Line length 133 for better readability
    - 'app/services/audit_results.rb' # line 35 is 121
    - 'app/services/checksum_validator.rb' # line 151 is 121
    - 'app/services/preserved_object_handler.rb' # line 269 is 121
    - 'app/services/workflow_errors_reporter.rb' # line 7 is 143
    - 'spec/lib/audit/moab_to_catalog_spec.rb' # 1 line 126
    - 'spec/models/endpoint_spec.rb' # line 83 is 123
    - 'spec/services/audit_results_spec.rb'
    - 'spec/services/checksum_validator_spec.rb'
    - 'spec/services/preserved_object_handler_check_exist_spec.rb' # 17 lines, but who's counting, officer?
    - 'spec/services/preserved_object_handler_confirm_version_spec.rb'
    - 'spec/services/preserved_object_handler_create_spec.rb'
    - 'spec/services/preserved_object_handler_spec.rb' # line 94 is 121
    - 'spec/services/preserved_object_handler_update_version_spec.rb'
    - 'spec/services/shared_examples_preserved_object_handler.rb'
    - 'spec/services/workflow_errors_reporter_spec.rb'

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'app/services/preserved_object_handler.rb' # check_existence shameless green
    - 'lib/audit/catalog_to_moab.rb' # check_catalog_version shameless green

Metrics/PerceivedComplexity:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # update_online_version shameless green
    - 'lib/audit/catalog_to_moab.rb' # check_catalog_version shameless green

# --- Naming ---

Naming/AccessorMethodName:
  Exclude:
    # rubocop doesn't like single param 'set_' methods, but this isn't an instace var setter, and nice to have method name be parallel to POH method
    - 'lib/audit/catalog_to_moab.rb'
Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'

# --- Performance ---

Performance/HashEachMethods:
  Exclude:
    - lib/audit/catalog_to_moab.rb # it's a tiny config object; code is clearer as is
    - lib/audit/checksum.rb # it's a tiny config object; code is clearer as is
    - lib/audit/moab_to_catalog.rb # it's a tiny config object; code is clearer as is

# --- Rails ---

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/audit/catalog_to_moab.rb' # use puts statements for following progress of long job
    - 'lib/audit/checksum.rb' # use puts statements for following progress of long job
    - 'lib/audit/moab_to_catalog.rb' # use puts statements for following progress of long job

# --- RSpec ---

RSpec/BeforeAfterAll:
  Exclude:
    # we use after(:all) specifically to prevent state leakage
    - 'spec/models/preservation_policy_spec.rb'

RSpec/ExampleLength:
  Max: 25

RSpec/InstanceVariable:
  Exclude:
    - 'spec/services/preserved_object_handler_update_version_spec.rb' # we can't use let instead of @

# we like 'expect(x).to receive' better than 'have_received'
RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Exclude:
    - 'spec/lib/audit/catalog_to_moab_instance_spec.rb'
    - 'spec/lib/audit/moab_to_catalog_spec.rb'
    - 'spec/models/preserved_copy_spec.rb'
    - 'spec/services/audit_results_spec.rb'
    - 'spec/services/preserved_object_handler_check_exist_spec.rb'
    - 'spec/services/preserved_object_handler_confirm_version_spec.rb'
    - 'spec/services/preserved_object_handler_create_spec.rb'
    - 'spec/services/preserved_object_handler_update_version_spec.rb'

# --- Style ---

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb' # that's how rspec-rails generates it

Style/BlockDelimiters:
  Exclude:
    - 'spec/*/*' # rspec expect statements look ugly with do-end instead of {}

Style/BracesAroundHashParameters:
  Exclude:
    - app/services/preserved_object_handler.rb # #update_status is clearer with the braces
    - lib/audit/catalog_to_moab.rb # #update_status is clearer with the braces

Style/Documentation:
  Exclude:
    - 'app/controllers/application_controller.rb' # that's how Rails generates it
    - 'app/helpers/application_helper.rb' # that's how Rails generates it
    - 'app/models/application_record.rb' # that's how Rails generates it
    - 'config/application.rb' # that's how Rails generates it

Style/FormatStringToken:
  EnforcedStyle: template # using interpolated strings in AuditResults

Style/GuardClause:
  Exclude:
    - app/services/preserved_object_handler.rb # update_status method easy to read as is
    - lib/audit/catalog_to_moab.rb # wrapping method on line 17 is more readable

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/spring.rb' # that's how Rails generates it

# because ' vs " isn't a big deal for readability or maintainability or execution time
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'Rakefile' # because [:spec, :rubocop] isn't a big deal
