# Turn on RSpec cops
require: rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  Include:
    - './Rakefile'
    - './config.ru'
    - '**/*.rb'
    - '**/*.rake'
  Exclude:
    - 'bin/**/*'
    - 'config/environments/*.rb'
    - 'db/**/*'
    - 'vendor/**/*'

# Turn on Rails cops
Rails:
  Enabled: true

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'app/services/preserved_object_handler.rb' # FIXME check_existence shameless green
    - '**/*.rake'
    - 'spec/**/*'

# because this isn't 1994
Metrics/LineLength:
  Max: 150
  Exclude:
    - 'app/services/audit_results.rb' # long lines for result code messgaes
    - 'app/services/checksum_validator.rb' # FIXME
    - 'lib/capistrano/tasks/capistrano-resque-pool.rake'
    - 'spec/controllers/catalog_controller_spec.rb' # FIXME
    - 'spec/jobs/moab_replication_audit_job_spec.rb' # line 32 regex is longer due to zmvs on an additional endpoint

Metrics/MethodLength:
  Max: 25

Naming/FileName:
  Exclude:
    - 'Capfile'
    - 'Gemfile'
    - 'lib/capistrano/tasks/capistrano-resque-pool.rake'

Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/ContextWording:
  Enabled: false # too dogmatic

RSpec/ExampleLength:
  Max: 25

RSpec/ImplicitSubject: # we use this for `define_enum_for`, `validate_presence_of`, etc.
  Enabled: false

# we like 'expect(x).to receive' better than 'have_received'
RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/jobs/integration_spec.rb' # line 30 testing additional zip_endpoint needs more expectations

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4 # default: 3
  Exclude:
    - 'spec/lib/audit/catalog_to_moab_spec.rb'
    - 'spec/lib/audit/moab_to_catalog_spec.rb'
    - 'spec/services/checksum_validator_spec.rb'
    - 'spec/services/preserved_object_handler_*.rb'

Style/AccessModifierDeclarations:
  Exclude:
    - 'config/initializers/okcomputer.rb' # atypical multi-class file

Style/BlockDelimiters:
  Exclude:
    - 'spec/*/*' # rspec expect statements look ugly with do-end instead of {}

# because ' vs " isn't a big deal for readability or maintainability or execution time
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'Rakefile' # because [:spec, :rubocop] isn't a big deal
    - '**/*.rake'
    - 'config/deploy/*'

Style/SymbolProc:
  Exclude:
    - app/jobs/plexer_job.rb # "Pass &:unreplicated! as an argument to find_or_create_by" - um, no.

Style/WordArray:
  Enabled: false # Naomi hates this rule;  "precious" ruby syntax
