version: '3.6'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - POSTGRES_HOST=db
      - REDIS_URL=redis:6379
      - RAILS_ENV=development
    volumes:
      - .:/app
      - ./tmp/pids:/app/tmp/pids
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:3
    command: redis-server
    ports:
      - 6379:6379
    volumes:
        - redis:/data
  gen_er_diagram:
    image: schemacrawler/schemacrawler
    entrypoint: /bin/bash
    # https://www.schemacrawler.com/diagramming.html
    # https://www.schemacrawler.com/docker-image.html
    # https://hub.docker.com/r/schemacrawler/schemacrawler/
    command: /opt/schemacrawler/schemacrawler.sh --server=postgresql --host=db --database=development --user=postgres --password=sekret --info-level=standard --command=schema --output-format=svg --output-file=/var/preservation_catalog/db/schema_er_diagram.svg --config-file=/var/preservation_catalog/db/schemacrawler.config.properties --title "PresCat Schema ER Diagram"
    volumes:
      - ./db:/var/preservation_catalog/db


volumes:
  redis:
  postgres-data:
